# -*- coding: utf-8 -*-
"""MLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRnH-y8S0n1mPjop_ttD50PT1voLi6xg
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df=pd.read_csv("Admission_Predict.csv")
Hours_Slept=df["TOEFL Score"].tolist()
Hours_Studied=df["GRE Score"].tolist()
results=df["Chance of admit"].tolist()

colors=[]
for data in results:
  if data==1:
    colors.append("green")
  else:
    colors.append("red")
fig=go.Figure(data=go.Scatter(
    x=Hours_Studied,
    y=Hours_Slept,
    mode="markers",
    marker=dict(color=colors)
))
fig.show()

hours=df[["TOEFL Score","GRE Score"]]
results=df[["Chance of admit"]]

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
hours_train,hours_test,results_train,results_test=train_test_split(hours,results,test_size=0.25,random_state=0)
print(hours_train)

classifier=LogisticRegression(random_state=0)
classifier.fit(hours_train,results_train)

results_predict=classifier.predict(hours_test)
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(results_test,results_predict))